<a href="https://colab.research.google.com/github/savagexr3/PyTorchDLML/blob/main/00_pytorch_fundamental_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Create Tensors

PyTorch are created using ```torch.Tensor()```

In [2]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get tensor back as Python int
scalar.item()

7

In [4]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR=torch.tensor([[[[1,2],[4,5],[6,7]]]])
TENSOR

tensor([[[[1, 2],
          [4, 5],
          [6, 7]]]])

In [16]:
TENSOR.ndim

4

In [17]:
TENSOR.shape

torch.Size([1, 1, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```

In [18]:
# Create a random tensor of size  (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5867, 0.1765, 0.8735, 0.2244],
        [0.2667, 0.1765, 0.3307, 0.6421],
        [0.7677, 0.0913, 0.1098, 0.5151]])

# New Section

In [19]:
# Create a random with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3,3))

tensor([[0.5756, 0.1195, 0.7119],
        [0.0350, 0.2502, 0.3533],
        [0.0233, 0.4722, 0.0295]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e.g. float32, float64)
                             device="cpu", # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`



In [33]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0316, 0.8057, 0.6787, 0.9243],
        [0.6857, 0.8859, 0.7508, 0.3489],
        [0.6112, 0.8221, 0.7157, 0.8715]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0316, 0.8057, 0.6787, 0.9243],
        [0.6857, 0.8859, 0.7508, 0.3489],
        [0.6112, 0.8221, 0.7157, 0.8715]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [35]:
# Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [37]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must watch:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [40]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4617, 0.5119, 0.2518],
        [0.3045, 0.4575, 0.1966],
        [0.0696, 0.6505, 0.1839]])

In [41]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [43]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 972 µs, sys: 794 µs, total: 1.77 ms
Wall time: 1.69 ms


In [45]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 53 µs, sys: 11 µs, total: 64 µs
Wall time: 67.2 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [46]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switched the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T,tensor_B.T.shape

In [ ]:
tensor_B,tensor_B.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

## Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x=torch.arange(1,100,10)
x.dtype

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean - note the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

## Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs
x.argmin()

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

In [ ]:
# Change the view
z=x.view(1,9)
z,z.shape

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input) )
z[:,0]=5
z,x

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimensions)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axie (or dim) order
x_permuted=x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

In [ ]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [47]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0],x[0,0]

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

In [ ]:
# index on x to return 3
x[:,0,2]

In [ ]:
# index on x to return 3, 6, 9
x[:,:,2]

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorchhas functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [55]:
# NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
# Change the value of array, what will this do to `tensor`?
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
# Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
# Change the tensor, what happens to `numpy_tensor`?
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially when the random seed does is "flavour" the randomness.

In [60]:
import torch

# Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8799, 0.1551, 0.8010, 0.3564],
        [0.4575, 0.1369, 0.2776, 0.9270],
        [0.9853, 0.0397, 0.4066, 0.6736]])
tensor([[0.7886, 0.4096, 0.8003, 0.7238],
        [0.7940, 0.5982, 0.6174, 0.4899],
        [0.9206, 0.9221, 0.7338, 0.3258]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [1]:
!nvidia-smi

Wed Feb 14 08:20:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [3]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [5]:
# Create a tensor (default on the CPU)
tensor=torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curiculum
https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

In [17]:
# Import torch
import torch

# Create random tensor
random_tensor_A=torch.rand(7,7)
random_tensor_A,random_tensor_A.shape

(tensor([[0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
         [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
         [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
         [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839],
         [0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993],
         [0.1100, 0.2541, 0.4333, 0.4451, 0.4966, 0.7865, 0.6604]]),
 torch.Size([7, 7]))

In [20]:
# Create another random tensor
random_tensor_B=torch.rand(1,7)
random_tensor_A,random_tensor_B

# Perform matrix multiplication
output=torch.mm(random_tensor_A,random_tensor_B.T)
output,output.shape

(tensor([[1.9494],
         [1.5918],
         [2.2140],
         [2.3937],
         [1.6017],
         [2.0558],
         [1.8340]]),
 torch.Size([7, 1]))

In [23]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A=torch.rand(7,7)
random_tensor_B=torch.rand(1,7)

# Matrix multiply tensors
output=torch.mm(random_tensor_A,random_tensor_B.T)
output,output.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [24]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [26]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [27]:
# Perform matmul on tensor_A and tensor_B
tensor_C=torch.mm(tensor_A,tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [30]:
# Find max
tensor_C.max(),tensor_C.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [31]:
# Find arg max and arg min
tensor_C.argmax(),tensor_C.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D=torch.rand(1,1,1,10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
