<a href="https://colab.research.google.com/github/savagexr3/PyTorchDLML/blob/main/00_pytorch_fundamental_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Create Tensors

PyTorch are created using ```torch.Tensor()```

In [2]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get tensor back as Python int
scalar.item()

7

In [4]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR=torch.tensor([[[[1,2],[4,5],[6,7]]]])
TENSOR

tensor([[[[1, 2],
          [4, 5],
          [6, 7]]]])

In [16]:
TENSOR.ndim

4

In [17]:
TENSOR.shape

torch.Size([1, 1, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```

In [18]:
# Create a random tensor of size  (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4294, 0.4485, 0.9626, 0.6479],
        [0.3891, 0.0189, 0.5703, 0.0363],
        [0.7551, 0.9634, 0.8317, 0.6538]])

In [19]:
# Create a random with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3,3))

tensor([[0.3322, 0.0379, 0.8353],
        [0.1008, 0.5881, 0.8808],
        [0.4633, 0.8404, 0.2071]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e.g. float32, float64)
                             device="cpu", # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [36]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`



In [37]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4181, 0.1850, 0.0548, 0.7205],
        [0.0174, 0.3663, 0.9424, 0.8231],
        [0.1729, 0.5547, 0.5638, 0.4861]])

In [38]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4181, 0.1850, 0.0548, 0.7205],
        [0.0174, 0.3663, 0.9424, 0.8231],
        [0.1729, 0.5547, 0.5638, 0.4861]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [47]:
# Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [48]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [49]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

In [50]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [51]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must watch:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [61]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.3220, 1.0964, 0.2739],
        [0.9289, 0.7785, 0.2028],
        [1.3249, 1.1212, 0.3029]])

In [53]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [54]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [55]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [57]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.94 ms, sys: 0 ns, total: 2.94 ms
Wall time: 2.74 ms


In [58]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 628 µs, sys: 20 µs, total: 648 µs
Wall time: 526 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [69]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's alias for writing less code)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [64]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switched the axes or dimensions of a given tensor.

In [68]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [70]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [71]:
# Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))